name: Test SSH/API port reachability

on:
  workflow_dispatch # Ovo omogućava da ga pokreneš ručno klikom

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: TCP check port 2255
        run: |
          timeout 5 bash -c "cat < /dev/null > /dev/tcp/ddwebapps.com/2083" && echo "REZULTAT: OPEN" || echo "REZULTAT: BLOCKED/TIMEOUT"
